export type V1FinalProvider="WHATSAPP"|"GOOGLE_CALENDAR"|"PAYMENT"|"EMAIL"|"WEBHOOK_N8N"|"AI";
export type V1FinalProviderMode="SANDBOX"|"LIVE";
export type V1FinalEvidenceKind="CONTROLLED_PROVIDER_RECEIPT"|"INJECTED_TRANSPORT"|"FIXTURE"|"AUTHORED_TEST";
export type V1FinalControlledProofManifest={provider:V1FinalProvider;operation:string;mode:V1FinalProviderMode;buildSha:string;capturedAt:string;redactedProviderReference:string;result:"PASS"|"FAIL";evidenceKind:V1FinalEvidenceKind;notes?:string[]};
const P:V1FinalProvider[]=["WHATSAPP","GOOGLE_CALENDAR","PAYMENT","EMAIL","WEBHOOK_N8N","AI"];
const op=(provider:V1FinalProvider,operation:string,mode:V1FinalProviderMode,description:string,sandboxOnly=false)=>({provider,operation,mode,description,sandboxOnly:sandboxOnly||undefined});
export const V1_FINAL_REQUIRED_PROVIDER_OPERATIONS=[
 op("WHATSAPP","inbound_signature","LIVE","Inbound signature"),op("WHATSAPP","durable_provider_receipt","LIVE","Durable provider receipt"),op("WHATSAPP","core_handoff","LIVE","Core handoff"),op("WHATSAPP","outbound_accepted","LIVE","Outbound accepted"),op("WHATSAPP","delivered_read_failure_callback","LIVE","Delivered/read/failure callback"),
 op("GOOGLE_CALENDAR","freebusy","LIVE","Fresh freebusy"),op("GOOGLE_CALENDAR","authoritative_visit_upsert","LIVE","Visit upsert"),op("GOOGLE_CALENDAR","cancellation","LIVE","Cancellation"),op("GOOGLE_CALENDAR","reconciliation_external_change_review","LIVE","External-change review"),op("GOOGLE_CALENDAR","stale_fresh_sync_behavior","LIVE","Stale/fresh sync"),
 op("PAYMENT","stripe_sandbox_checkout","SANDBOX","Stripe sandbox checkout",true),op("PAYMENT","verified_sandbox_webhook","SANDBOX","Verified sandbox webhook",true),op("PAYMENT","core_payment_application","SANDBOX","Core payment application",true),op("PAYMENT","duplicate_idempotency","SANDBOX","Duplicate/idempotency",true),
 op("EMAIL","accepted_send","LIVE","Accepted send"),op("EMAIL","delivered_callback","LIVE","Delivered callback"),op("EMAIL","soft_bounce","LIVE","Soft bounce"),op("EMAIL","hard_bounce_complaint","LIVE","Hard bounce/complaint"),op("EMAIL","suppression_recovery","LIVE","Suppression/recovery"),
 op("WEBHOOK_N8N","authoritative_endpoint","LIVE","Authoritative endpoint"),op("WEBHOOK_N8N","signature","LIVE","Signature"),op("WEBHOOK_N8N","delivery","LIVE","Delivery"),op("WEBHOOK_N8N","retry_classification","LIVE","Retry classification"),op("WEBHOOK_N8N","pending_state","LIVE","Pending state"),op("WEBHOOK_N8N","completion_callback","LIVE","Completion callback"),
 op("AI","provider_model_health","LIVE","Model health"),op("AI","controlled_extraction_intent","LIVE","Extraction/intent"),op("AI","no_business_authority","LIVE","AI cannot own price/payment/roles/booking/provider truth")];
const cfg:any={WHATSAPP:["Meta app/account IDs","signature/app secret reference","access token reference","controlled sender/recipient","callback URL/verify token"],GOOGLE_CALENDAR:["OAuth client reference","redirect URI","refresh token/test account reference","test calendar","freebusy/events scopes","fresh sync state"],PAYMENT:["Stripe sandbox configuration only","sandbox webhook signing reference","controlled sandbox checkout"],EMAIL:["provider account/API key reference","verified sender/domain","callback signing/auth reference","controlled recipient"],WEBHOOK_N8N:["authoritative endpoint registry entry","signing-secret reference","allowed host entry","n8n workflow ID","completion callback mapping"],AI:["model/provider key reference","model health endpoint","controlled extraction fixture","no-business-authority confirmation"]};
const secret=/(sk_live_|sk_test_|whsec_|Bearer\s+|access_token|refresh_token|client_secret|api[_-]?key\s*[:=]|signing[_-]?secret\s*[:=]|xox[baprs]-|AIza[0-9A-Za-z_-]+)/i;
const k=(p:V1FinalProvider,o:string)=>`${p}:${o}`;const sha=(s:string)=>/^[a-f0-9]{7,64}$/i.test(s);const ms=(s:string)=>new Date(s).getTime();
export function validateFinalControlledProofManifest(i:{manifest:V1FinalControlledProofManifest;acceptedBuildSha:string;now:string;maxAgeHours?:number}){const m=i.manifest,r=V1_FINAL_REQUIRED_PROVIDER_OPERATIONS.find(x=>x.provider===m.provider&&x.operation===m.operation);if(!r)return{ok:false,manifest:m,code:"UNKNOWN_OPERATION",message:"Operation is outside the final V1 matrix."};if(!sha(i.acceptedBuildSha)||!sha(m.buildSha)||m.buildSha!==i.acceptedBuildSha)return{ok:false,manifest:m,code:"BUILD_SHA_MISMATCH",message:"Proof must bind the accepted final candidate SHA."};if(m.result!=="PASS")return{ok:false,manifest:m,code:"PROOF_NOT_PASSING",message:"Only PASS proofs can satisfy controlled proof."};if(m.evidenceKind!=="CONTROLLED_PROVIDER_RECEIPT")return{ok:false,manifest:m,code:"NOT_PROVIDER_RECEIPT",message:"Fixture/injected/authored evidence cannot be provider proof."};if(m.provider==="PAYMENT"&&m.mode==="LIVE")return{ok:false,manifest:m,code:"STRIPE_LIVE_POLICY_INVALID",message:"Stripe remains SANDBOX/DEMO only."};if(m.mode!==r.mode)return{ok:false,manifest:m,code:"MODE_MISMATCH",message:"Manifest mode does not match the required operation."};if(!m.redactedProviderReference||m.redactedProviderReference.length<4)return{ok:false,manifest:m,code:"MISSING_REDACTED_REFERENCE",message:"A redacted provider reference is required."};if(secret.test(JSON.stringify(m)))return{ok:false,manifest:m,code:"SECRET_BEARING_PROOF",message:"Proof manifest contains secret-like material."};const c=ms(m.capturedAt),n=ms(i.now);if(!Number.isFinite(c)||!Number.isFinite(n))return{ok:false,manifest:m,code:"INVALID_TIMESTAMP",message:"Proof timestamps must be valid."};if(c>n||n-c>(i.maxAgeHours??72)*3600000)return{ok:false,manifest:m,code:"STALE_PROOF",message:"Proof is stale or future-dated."};return{ok:true,manifest:m}}
export function buildFinalV1ProviderEvidencePacket(i:{buildSha:string;manifests:V1FinalControlledProofManifest[];now:string}){const vals=i.manifests.map(m=>validateFinalControlledProofManifest({manifest:m,acceptedBuildSha:i.buildSha,now:i.now}));const accepted=new Map(vals.filter((v:any)=>v.ok&&v.manifest).map((v:any)=>[k(v.manifest.provider,v.manifest.operation),v.manifest]));const verifiedOperations:any[]=[],missingOperations:any[]=[],sandboxOnlyOperations:any[]=[],blockers:string[]=[];for(const r of V1_FINAL_REQUIRED_PROVIDER_OPERATIONS){const proof=accepted.get(k(r.provider,r.operation));if(proof)(r.sandboxOnly?sandboxOnlyOperations:verifiedOperations).push({provider:r.provider,operation:r.operation,mode:r.mode,status:r.sandboxOnly?"SANDBOX_ONLY":"VERIFIED",proofReference:proof.redactedProviderReference,capturedAt:proof.capturedAt});else{const e={provider:r.provider,operation:r.operation,mode:r.mode,status:r.sandboxOnly?"SANDBOX_ONLY":"MISSING",blocker:r.sandboxOnly?"SANDBOX_CONTROLLED_PROOF_REQUIRED":"CONTROLLED_PROVIDER_PROOF_REQUIRED"};(r.sandboxOnly?sandboxOnlyOperations:missingOperations).push(e);blockers.push(`${r.provider}:${r.operation}:${e.blocker}`)}}const staleOrMismatchedEvidence=vals.filter((v:any)=>!v.ok);if(staleOrMismatchedEvidence.length)blockers.push("STALE_OR_MISMATCHED_EVIDENCE_REJECTED");return{buildSha:i.buildSha,requiredOperations:V1_FINAL_REQUIRED_PROVIDER_OPERATIONS,verifiedOperations,missingOperations,sandboxOnlyOperations,staleOrMismatchedEvidence,blockers,overallControlledProviderGate:blockers.length?"CONFIGURATION_BLOCKED":"READY"}}
export function auditFinalConnectorContractDrift(i:any){const e:any={coreDtos:["RequestDTO","QuoteDTO","VisitDTO","ConversationDTO","InvoiceDTO","IntegrationStatusDTO","RecurrenceRuleDTO","QualityCaseDTO","UsageMetricDTO"],outboxTopics:["conversation.reply","calendar.visit.upsert","calendar.visit.cancel","visit.reminder","recurrence.visit.materialized","manual_payment.recorded","quality.review.requested","webhook.delivery"],deliveryPurposes:["QUOTE","CONFIRMATION","VISIT_REMINDER","INVOICE","FEEDBACK","CUSTOMER_REPLY","CALENDAR_VISIT"],visitProjectionFields:["workspaceId","visitId","crewId","startAt","endAt","timezone","idempotencyKey","providerMappingKey","canMutateBookingTruth"],productIntegrationProviders:["WHATSAPP","GOOGLE_CALENDAR","PAYMENT","EMAIL","WEBHOOK","AI"]};const miss=[...e.coreDtos.filter((x:string)=>!i.coreDtos.includes(x)).map((x:string)=>`coreDtos:${x}`),...e.outboxTopics.filter((x:string)=>!i.outboxTopics.includes(x)).map((x:string)=>`outboxTopics:${x}`),...e.deliveryPurposes.filter((x:string)=>!i.deliveryPurposes.includes(x)).map((x:string)=>`deliveryPurposes:${x}`),...e.visitProjectionFields.filter((x:string)=>!i.visitProjectionFields.includes(x)).map((x:string)=>`visitProjectionFields:${x}`),...e.productIntegrationProviders.filter((x:string)=>!i.productIntegrationProviders.includes(x)).map((x:string)=>`productIntegrationProviders:${x}`),...(i.usageLimitedOutboundPath?[]:["usageLimitedOutboundPath:missing"] )];return{pass:miss.length===0,missing:miss,checked:Object.values(e).flat(),coordinatorBlockers:miss.map((x:string)=>`COORDINATOR_CONTRACT_DRIFT:${x}`)}}
export function buildFinalCrossProviderPreflight(i:any){const raw:any[]=[ ["enquiry","WHATSAPP","inbound_signature"],["AI extraction","AI","controlled_extraction_intent"],["deterministic quote","AI","no_business_authority"],["calendar availability","GOOGLE_CALENDAR","freebusy"],["sandbox deposit","PAYMENT","stripe_sandbox_checkout"],["confirmation","WHATSAPP","outbound_accepted"],["reminders","EMAIL","accepted_send"],["calendar visit","GOOGLE_CALENDAR","authoritative_visit_upsert"],["crew work"],["quality"],["manual payment","PAYMENT","core_payment_application"],["optional n8n","WEBHOOK_N8N","delivery"] ];const steps=raw.map(([step,provider,operation])=>({step,provider,operation,status:provider&&!i.contractEvidenceProviders.includes(provider)?"CONTRACT_BLOCKED":"CONTRACT_READY"}));const blockers=[...steps.filter(s=>s.status==="CONTRACT_BLOCKED").map(s=>`${s.provider}:${s.operation}:CONTRACT_EVIDENCE_MISSING`),...i.contractDrift.coordinatorBlockers];return{buildSha:i.buildSha,pass:blockers.length===0,mutatesCoreTruth:false,providerVerifiedClaim:false,contractEvidenceOnly:true,steps,blockers}}
export function buildFinalProviderGateReport(packet:any,contractEvidenceProviders:V1FinalProvider[]){return P.map(provider=>{const req=packet.requiredOperations.filter((r:any)=>r.provider===provider),missing=packet.missingOperations.filter((m:any)=>m.provider===provider),sandbox=packet.sandboxOnlyOperations.filter((s:any)=>s.provider===provider),allSandbox=req.every((r:any)=>r.sandboxOnly),complete=missing.length===0&&(!allSandbox||sandbox.every((s:any)=>s.proofReference)),ops=[...missing,...sandbox.filter((s:any)=>!s.proofReference)].map((x:any)=>x.operation).join(", ")||"none";return{provider,implementationStatus:"IMPLEMENTED",contractStatus:contractEvidenceProviders.includes(provider)?"CONTRACT_TESTED":"CONTRACT_EVIDENCE_MISSING",controlledProofStatus:allSandbox?"SANDBOX_ONLY":complete?"COMPLETE":"MISSING",missingConfiguration:cfg[provider],nextOwnerAction:provider==="PAYMENT"?`Run Stripe sandbox proof only for: ${ops}; do not request live Stripe.`:`Provide controlled ${provider} access/receipts for: ${ops}.`}})}
export function buildFinalControlledProviderGate(packet:any){return[...packet.missingOperations,...packet.sandboxOnlyOperations.filter((x:any)=>!x.proofReference)].map((x:any)=>`${x.provider}:${x.operation}`).join("; ")}
export function buildFinalProviderAcceptanceReport(i:any){const packet=buildFinalV1ProviderEvidencePacket({buildSha:i.buildSha,manifests:i.manifests,now:i.now}),contractDrift=auditFinalConnectorContractDrift(i.contractDrift),preflight=buildFinalCrossProviderPreflight({buildSha:i.buildSha,contractEvidenceProviders:i.contractEvidenceProviders,contractDrift}),providerGateReport=buildFinalProviderGateReport(packet,i.contractEvidenceProviders);return{buildSha:i.buildSha,packet,preflight,contractDrift,providerGateReport,controlledProviderGate:buildFinalControlledProviderGate(packet),state:preflight.pass?"CONTRACT_TESTED":"IMPLEMENTED",canonicalGate:packet.overallControlledProviderGate==="READY"?"READY":"CONFIGURATION_BLOCKED",noFalseProviderClaims:packet.staleOrMismatchedEvidence.every((x:any)=>!x.ok)}}
export function buildFinalExternalAccessChecklist(report:any[]){return report.filter(r=>r.provider!=="PAYMENT").map(r=>`${r.provider}: ${r.nextOwnerAction} Missing config/access: ${r.missingConfiguration.join("; ")}`).concat("PAYMENT: Run Stripe-style SANDBOX checkout/webhook/idempotency/application proof only; do not request live Stripe under current owner policy.")}
