export type ProductBacking = "FIXTURE" | "SERVER" | "SANDBOX_PROVIDER" | "LIVE_PROVIDER" | "CONFIGURATION_BLOCKED";
export type ProductEvidenceState = "DTO_READ" | "COMMAND_PENDING" | "COMMAND_RESULT" | "PROVIDER_CHECKOUT_LAUNCHED" | "PROVIDER_RECEIPT_REQUIRED" | "HUMAN_REVIEW" | "BROWSER_TO_RUN";
export interface FinalJourneyStep { id: string; surface: string; route: string; authoritativeSource: string; requiredReadOrCommand: string; evidenceState: ProductEvidenceState; backing: ProductBacking; expectedRecovery: string; nextRouteOrAction: string; }
export const finalGuidedV1Journey: FinalJourneyStep[] = [
  { id: "public-enquiry", surface: "visitor", route: "/[business]/enquire", authoritativeSource: "RequestDTO", requiredReadOrCommand: "createRequest/updateRequest", evidenceState: "COMMAND_RESULT", backing: "SERVER", expectedRecovery: "validation_error keeps visitor on enquiry", nextRouteOrAction: "deterministic quote" },
  { id: "deterministic-quote", surface: "staff", route: "/app/[workspace]/quotes", authoritativeSource: "QuoteDTO", requiredReadOrCommand: "calculateQuote/sendQuote", evidenceState: "COMMAND_RESULT", backing: "SERVER", expectedRecovery: "version_conflict requires refresh", nextRouteOrAction: "customer accept quote" },
  { id: "customer-accept-quote", surface: "customer", route: "/portal/quotes/[id]", authoritativeSource: "QuoteDTO.version", requiredReadOrCommand: "acceptQuote", evidenceState: "COMMAND_RESULT", backing: "SERVER", expectedRecovery: "quote not found/expired/version conflict/unauthorized accept shows action state", nextRouteOrAction: "find slots" },
  { id: "find-slots", surface: "customer", route: "/portal/booking", authoritativeSource: "SlotDTO[]", requiredReadOrCommand: "findSlots", evidenceState: "DTO_READ", backing: "SERVER", expectedRecovery: "no slots or stale availability keeps booking pending", nextRouteOrAction: "hold slot" },
  { id: "hold-slot", surface: "customer", route: "/portal/booking", authoritativeSource: "holdId/expiresAt", requiredReadOrCommand: "holdSlot", evidenceState: "COMMAND_RESULT", backing: "SERVER", expectedRecovery: "hold conflict/expired requires refreshed availability", nextRouteOrAction: "sandbox checkout launch" },
  { id: "sandbox-checkout-launch", surface: "customer", route: "/portal/booking", authoritativeSource: "safe checkout launch output", requiredReadOrCommand: "launchSandboxCheckout", evidenceState: "PROVIDER_CHECKOUT_LAUNCHED", backing: "SANDBOX_PROVIDER", expectedRecovery: "checkout configuration blocked/sandbox failure/payment pending never marks paid", nextRouteOrAction: "verified webhook" },
  { id: "verified-webhook", surface: "system", route: "provider callback", authoritativeSource: "VerifiedPaymentEvent", requiredReadOrCommand: "applyVerifiedPayment", evidenceState: "PROVIDER_RECEIPT_REQUIRED", backing: "SANDBOX_PROVIDER", expectedRecovery: "payment review/deduplication/amount mismatch stays Core-owned", nextRouteOrAction: "invoice and visit confirmation" },
  { id: "invoice-visit-confirmation", surface: "customer/staff", route: "/portal/invoices/[id]", authoritativeSource: "InvoiceDTO/VisitDTO", requiredReadOrCommand: "readWorkspaceSnapshot", evidenceState: "DTO_READ", backing: "SERVER", expectedRecovery: "receipt hidden until authoritative InvoiceDTO/VisitDTO prove it", nextRouteOrAction: "crew/quality/reporting" },
  { id: "inbox", surface: "dispatcher", route: "/app/[workspace]/inbox", authoritativeSource: "ConversationDTO/MessageDTO", requiredReadOrCommand: "readWorkspaceSnapshot/setConversationHandover/enqueueConversationReply", evidenceState: "COMMAND_RESULT", backing: "SERVER", expectedRecovery: "reply suppressed or version conflict shows refresh/recovery", nextRouteOrAction: "CRM" },
  { id: "crew-job", surface: "crew", route: "/crew/jobs/[id]", authoritativeSource: "VisitDTO.version", requiredReadOrCommand: "transitionVisit", evidenceState: "COMMAND_RESULT", backing: "SERVER", expectedRecovery: "invalid transition/version conflict requires refresh", nextRouteOrAction: "field evidence" },
  { id: "field-evidence", surface: "crew", route: "/crew/jobs/[id]", authoritativeSource: "VisitEvidenceDTO/VisitChecklistItemDTO", requiredReadOrCommand: "readWorkspaceSnapshot", evidenceState: "DTO_READ", backing: "CONFIGURATION_BLOCKED", expectedRecovery: "submission disabled until Core evidence command is accepted", nextRouteOrAction: "quality" },
  { id: "quality", surface: "dispatcher", route: "/app/[workspace]/quality", authoritativeSource: "QualityCaseDTO.version", requiredReadOrCommand: "applyQualityCaseAction", evidenceState: "COMMAND_RESULT", backing: "SERVER", expectedRecovery: "resolution required/state conflict shows no optimistic mutation", nextRouteOrAction: "manual payment/recovery" },
  { id: "invoice-manual-payment", surface: "dispatcher/owner", route: "/app/[workspace]/invoices", authoritativeSource: "InvoiceDTO.version", requiredReadOrCommand: "applyManualPayment", evidenceState: "COMMAND_RESULT", backing: "SERVER", expectedRecovery: "amount/currency/version conflict stays server-owned", nextRouteOrAction: "recovery" },
  { id: "recovery", surface: "dispatcher/owner", route: "/app/[workspace]/automations", authoritativeSource: "AttentionItemDTO/integration state", requiredReadOrCommand: "readWorkspaceSnapshot/provider reconciliation", evidenceState: "HUMAN_REVIEW", backing: "CONFIGURATION_BLOCKED", expectedRecovery: "uncertain provider state requires operator reconciliation before retry", nextRouteOrAction: "reports" },
  { id: "reports", surface: "owner/dispatcher", route: "/app/[workspace]/reports", authoritativeSource: "ReportingSnapshotDTO", requiredReadOrCommand: "readReportingSnapshot", evidenceState: "DTO_READ", backing: "SERVER", expectedRecovery: "invalid date range/no data handled by action state", nextRouteOrAction: "platform billing" },
  { id: "platform-billing", surface: "owner", route: "/app/[workspace]/billing", authoritativeSource: "PlatformBillingSnapshotDTO", requiredReadOrCommand: "readPlatformBillingSnapshot", evidenceState: "DTO_READ", backing: "SERVER", expectedRecovery: "sandbox/configuration state never becomes customer payment truth", nextRouteOrAction: "settings" },
  { id: "settings", surface: "owner", route: "/app/[workspace]/settings", authoritativeSource: "OwnerSettingsSnapshotDTO", requiredReadOrCommand: "readOwnerSettingsSnapshot", evidenceState: "DTO_READ", backing: "SERVER", expectedRecovery: "missing provider configuration remains explicitly blocked", nextRouteOrAction: "onboarding" },
  { id: "onboarding", surface: "owner", route: "/onboarding", authoritativeSource: "OwnerSettingsSnapshotDTO/integration readiness", requiredReadOrCommand: "read readiness state", evidenceState: "HUMAN_REVIEW", backing: "CONFIGURATION_BLOCKED", expectedRecovery: "launch stays blocked until required configuration/evidence exists", nextRouteOrAction: "release readiness" }
];
export const finalRoleRouteMatrix = [
  { role: "visitor", allowed: ["public-enquiry"], blocked: ["manual payment", "quality mutation", "platform billing", "inbox"] },
  { role: "customer", allowed: ["customer-accept-quote", "find-slots", "hold-slot", "sandbox-checkout-launch", "customer invoice"], blocked: ["staff manual payment", "quality mutation", "reports", "platform billing"] },
  { role: "crew", allowed: ["crew job", "field evidence", "accepted crew transitions"], blocked: ["reports", "platform billing", "inbox", "owner settings"] },
  { role: "dispatcher", allowed: ["attention", "inbox", "crm", "quotes", "schedule", "jobs", "manual payment boundary", "quality", "recovery", "reports"], blocked: ["owner-only platform billing/settings mutations"] },
  { role: "owner", allowed: ["all workspace/admin read surfaces", "settings", "platform billing", "onboarding"], blocked: ["unverified live provider claims"] }
] as const;
export const finalErrorRecoveryMatrix = ["authorization", "workspace mismatch", "version conflict", "quote not found", "quote expired", "no slots", "slot stale", "hold conflict", "hold expired", "checkout configuration blocked", "checkout sandbox failure", "payment still pending", "payment review", "calendar stale", "provider config blocked", "reply suppressed", "usage limit reached", "quality resolution required", "recurrence conflict", "server failure"].map((name) => ({ name, optimisticMutation: false, recovery: "show typed Product action/recovery state and require authoritative server/provider evidence before business state changes" }));
