export type ProductBacking = "FIXTURE" | "SERVER" | "SANDBOX_PROVIDER" | "LIVE_PROVIDER" | "CONFIGURATION_BLOCKED";
export type ProductEvidenceState = "DTO_READ" | "COMMAND_PENDING" | "COMMAND_RESULT" | "PROVIDER_RECEIPT_REQUIRED" | "HUMAN_REVIEW" | "BROWSER_TO_RUN";
export interface FinalJourneyStep { id: string; surface: string; route: string; authoritativeSource: string; requiredReadOrCommand: string; evidenceState: ProductEvidenceState; backing: ProductBacking; expectedRecovery: string; nextRouteOrAction: string; }
export const finalGuidedV1Journey: FinalJourneyStep[] = [
  { id: "public-enquiry", surface: "visitor", route: "/[business]/enquire", authoritativeSource: "RequestDTO/QuoteDTO", requiredReadOrCommand: "createRequest/updateRequest/calculateQuote", evidenceState: "COMMAND_RESULT", backing: "SERVER", expectedRecovery: "validation_error keeps visitor on enquiry", nextRouteOrAction: "request summary" },
  { id: "request-summary", surface: "visitor/customer", route: "request summary", authoritativeSource: "RequestDTO + QuoteDTO", requiredReadOrCommand: "readWorkspaceSnapshot", evidenceState: "DTO_READ", backing: "SERVER", expectedRecovery: "missing quote shows server boundary", nextRouteOrAction: "quote" },
  { id: "quote", surface: "customer", route: "/portal/quote", authoritativeSource: "QuoteDTO.version", requiredReadOrCommand: "sendQuote/quote acceptance boundary", evidenceState: "COMMAND_RESULT", backing: "SERVER", expectedRecovery: "version_conflict requires refresh", nextRouteOrAction: "slot/checkout" },
  { id: "slot-checkout", surface: "customer", route: "/portal/booking", authoritativeSource: "SlotDTO/VisitDTO/InvoiceDTO", requiredReadOrCommand: "findSlots/holdSlot/applyVerifiedPayment", evidenceState: "PROVIDER_RECEIPT_REQUIRED", backing: "SANDBOX_PROVIDER", expectedRecovery: "slot stale or hold expired returns to schedule", nextRouteOrAction: "customer overview" },
  { id: "customer-overview", surface: "customer", route: "/portal", authoritativeSource: "WorkspaceSnapshot", requiredReadOrCommand: "readWorkspaceSnapshot", evidenceState: "DTO_READ", backing: "SERVER", expectedRecovery: "snapshot_auth_failed shows portal boundary", nextRouteOrAction: "customer invoice" },
  { id: "customer-invoice", surface: "customer", route: "/portal/invoices/[id]", authoritativeSource: "InvoiceDTO", requiredReadOrCommand: "readWorkspaceSnapshot", evidenceState: "DTO_READ", backing: "SERVER", expectedRecovery: "manual payment disabled for customer", nextRouteOrAction: "staff attention" },
  { id: "staff-attention", surface: "dispatcher", route: "/app/[workspace]", authoritativeSource: "AttentionItemDTO/IntegrationStatusDTO", requiredReadOrCommand: "readWorkspaceSnapshot", evidenceState: "DTO_READ", backing: "SERVER", expectedRecovery: "calendar stale/provider blocked stay human-owned", nextRouteOrAction: "inbox" },
  { id: "inbox", surface: "dispatcher", route: "/app/[workspace]/inbox", authoritativeSource: "ConversationDTO/MessageDTO", requiredReadOrCommand: "readWorkspaceSnapshot/setConversationHandover/enqueueConversationReply", evidenceState: "COMMAND_RESULT", backing: "SERVER", expectedRecovery: "reply suppressed or version conflict shows refresh/recovery", nextRouteOrAction: "CRM" },
  { id: "crm", surface: "dispatcher", route: "/app/[workspace]/customers", authoritativeSource: "RequestDTO/ConversationDTO", requiredReadOrCommand: "readWorkspaceSnapshot", evidenceState: "DTO_READ", backing: "SERVER", expectedRecovery: "workspace mismatch rejected", nextRouteOrAction: "quotes" },
  { id: "quotes", surface: "dispatcher", route: "/app/[workspace]/quotes", authoritativeSource: "QuoteDTO", requiredReadOrCommand: "sendQuote", evidenceState: "COMMAND_RESULT", backing: "SERVER", expectedRecovery: "version conflict requires reload", nextRouteOrAction: "schedule" },
  { id: "schedule", surface: "dispatcher", route: "/app/[workspace]/schedule", authoritativeSource: "SlotDTO/VisitDTO", requiredReadOrCommand: "findSlots/holdSlot", evidenceState: "COMMAND_RESULT", backing: "SERVER", expectedRecovery: "slot unavailable or stale calendar keeps schedule pending", nextRouteOrAction: "jobs" },
  { id: "jobs", surface: "dispatcher", route: "/app/[workspace]/jobs", authoritativeSource: "VisitDTO", requiredReadOrCommand: "readWorkspaceSnapshot", evidenceState: "DTO_READ", backing: "SERVER", expectedRecovery: "wrong workspace rejected", nextRouteOrAction: "crew today" },
  { id: "crew-today", surface: "crew", route: "/crew/today", authoritativeSource: "VisitDTO", requiredReadOrCommand: "readWorkspaceSnapshot", evidenceState: "DTO_READ", backing: "SERVER", expectedRecovery: "unauthorized crew blocked", nextRouteOrAction: "crew job" },
  { id: "crew-job", surface: "crew", route: "/crew/jobs/[id]", authoritativeSource: "VisitDTO.version", requiredReadOrCommand: "transitionVisit", evidenceState: "COMMAND_RESULT", backing: "SERVER", expectedRecovery: "invalid transition/version conflict requires refresh", nextRouteOrAction: "field evidence" },
  { id: "field-evidence", surface: "crew", route: "/crew/jobs/[id]", authoritativeSource: "VisitEvidenceDTO/VisitChecklistItemDTO", requiredReadOrCommand: "readWorkspaceSnapshot", evidenceState: "DTO_READ", backing: "CONFIGURATION_BLOCKED", expectedRecovery: "submission disabled until Core evidence command is accepted", nextRouteOrAction: "recurrence" },
  { id: "recurrence", surface: "staff", route: "/app/[workspace]/settings", authoritativeSource: "RecurrenceRuleDTO/VisitDTO", requiredReadOrCommand: "createRecurrenceRule/applyRecurrenceRuleAction", evidenceState: "COMMAND_RESULT", backing: "SERVER", expectedRecovery: "recurrence conflict/skip unavailable shows action state", nextRouteOrAction: "invoice" },
  { id: "invoice-manual-payment", surface: "dispatcher", route: "/app/[workspace]/invoices", authoritativeSource: "InvoiceDTO.version", requiredReadOrCommand: "applyManualPayment", evidenceState: "COMMAND_RESULT", backing: "SERVER", expectedRecovery: "paid/void/amount/currency mismatch remains server-owned", nextRouteOrAction: "quality" },
  { id: "quality", surface: "dispatcher", route: "/app/[workspace]/quality", authoritativeSource: "QualityCaseDTO.version", requiredReadOrCommand: "applyQualityCaseAction", evidenceState: "COMMAND_RESULT", backing: "SERVER", expectedRecovery: "resolution required/state conflict shows no optimistic mutation", nextRouteOrAction: "recovery" },
  { id: "recovery", surface: "dispatcher", route: "/app/[workspace]/automations", authoritativeSource: "AttentionItemDTO/IntegrationStatusDTO", requiredReadOrCommand: "readWorkspaceSnapshot", evidenceState: "HUMAN_REVIEW", backing: "SERVER", expectedRecovery: "no automated recovery command is invented", nextRouteOrAction: "reports" },
  { id: "reports", surface: "owner/dispatcher", route: "/app/[workspace]/reports", authoritativeSource: "ReportingSnapshotDTO", requiredReadOrCommand: "readReportingSnapshot", evidenceState: "DTO_READ", backing: "SERVER", expectedRecovery: "invalid date range/no data handled by action state", nextRouteOrAction: "platform billing" },
  { id: "platform-billing", surface: "owner", route: "/app/[workspace]/billing", authoritativeSource: "PlatformBillingSnapshotDTO", requiredReadOrCommand: "readPlatformBillingSnapshot", evidenceState: "DTO_READ", backing: "SANDBOX_PROVIDER", expectedRecovery: "usage limit reached/sandbox not live remains labelled", nextRouteOrAction: "settings" },
  { id: "settings", surface: "owner", route: "/app/[workspace]/settings", authoritativeSource: "OwnerSettingsSnapshotDTO/IntegrationStatusDTO", requiredReadOrCommand: "readOwnerSettingsSnapshot", evidenceState: "DTO_READ", backing: "SERVER", expectedRecovery: "missing service/team setup is owner input", nextRouteOrAction: "onboarding" },
  { id: "onboarding", surface: "owner", route: "/onboarding", authoritativeSource: "OwnerSettingsSnapshotDTO/IntegrationStatusDTO", requiredReadOrCommand: "readOwnerSettingsSnapshot", evidenceState: "DTO_READ", backing: "CONFIGURATION_BLOCKED", expectedRecovery: "SANDBOX/BLOCKED/REAUTH_REQUIRED cannot claim live readiness", nextRouteOrAction: "browser acceptance" }
];
export const finalRoleRouteMatrix = [
  { role: "visitor", allowed: ["public-enquiry", "request-summary", "quote", "slot-checkout"], blocked: ["manual payment", "quality mutation", "platform billing", "inbox"] },
  { role: "customer", allowed: ["customer-overview", "customer-invoice", "preferences"], blocked: ["staff manual payment", "quality mutation", "reports", "platform billing"] },
  { role: "crew", allowed: ["crew-today", "crew-job", "field-evidence", "accepted crew transitions"], blocked: ["reports", "platform billing", "inbox", "owner settings"] },
  { role: "dispatcher", allowed: ["attention", "inbox", "crm", "quotes", "schedule", "jobs", "manual payment boundary", "quality", "recovery", "reports"], blocked: ["owner-only platform billing/settings mutations"] },
  { role: "owner", allowed: ["all workspace/admin read surfaces", "settings", "platform billing", "onboarding"], blocked: ["unverified live provider claims"] }
] as const;
export const finalErrorRecoveryMatrix = ["authorization", "workspace mismatch", "version conflict", "slot stale", "hold expired", "payment review", "calendar stale", "provider config blocked", "reply suppressed", "usage limit reached", "quality resolution required", "recurrence conflict", "server failure"].map((name) => ({ name, optimisticMutation: false, recovery: "show typed Product action/recovery state and require authoritative server/provider evidence before business state changes" }));
