import type { InvoiceDTO, QuoteDTO, SlotDTO, VisitDTO } from "@/contracts";
import type { HeldSlotOutcome } from "@/features/schedule/customer-booking-boundary";
import { buildCheckoutView, type CheckoutProviderMode } from "./view-models";
import type { SandboxCheckoutLaunchOutput } from "./sandbox-checkout-boundary";
interface CheckoutPreviewProps { quote: QuoteDTO; slot: SlotDTO; visit: VisitDTO; invoice: InvoiceDTO; paymentMode: CheckoutProviderMode; holdExpiresAt: string; heldSlot?: HeldSlotOutcome; sandboxCheckoutHandlerInjected?: boolean; sandboxCheckoutPending?: boolean; sandboxCheckout?: SandboxCheckoutLaunchOutput; now?: string }
export function CheckoutPreview(props?: CheckoutPreviewProps) {
  if (!props) return <section className="checkout-panel" aria-label="Customer checkout state preview"><div><p className="eyebrow">Checkout state · server data required</p><h2>Checkout waits for accepted quote, authoritative hold and sandbox handler.</h2><p>No hosted checkout command or provider receipt is exposed from this reusable component.</p></div><button className="button-primary full" type="button" disabled aria-disabled="true">Checkout unavailable · server data required</button></section>;
  const view = buildCheckoutView({ ...props, paymentMode: "SANDBOX" });
  return <section className="checkout-panel" aria-label="Customer checkout state preview"><div><p className="eyebrow">Checkout state · SANDBOX</p><h2>Accept quote, hold slot, then launch sandbox checkout.</h2><p>{view.warning}</p></div><div className="checkout-steps" role="list" aria-label="Checkout steps"><article role="listitem" className="plain-card"><span className="status-pill success">Quote</span><h3>{view.quoteState}</h3><p>Deposit {view.depositLabel}; balance {view.balanceLabel}</p></article><article role="listitem" className="plain-card"><span className="status-pill attention">Slot hold</span><h3>{view.slotState}</h3><p>{view.holdLabel}</p></article><article role="listitem" className="plain-card"><span className="status-pill pending">Payment</span><h3>{view.paymentState}</h3><p>{view.canShowReceipt ? "Verified receipt can be shown." : "Payment pending until verified webhook/Core payment flow updates business DTOs."}</p>{view.checkoutUrl && <a className="button-secondary full" href={view.checkoutUrl}>Open sandbox checkout</a>}{view.providerSessionLabel && <p>{view.providerSessionLabel}</p>}</article><article role="listitem" className="plain-card"><span className="status-pill pending">Visit</span><h3>{view.visitState}</h3><button className="button-primary full" type="button" disabled={!view.checkoutAvailability.enabled} aria-disabled={!view.checkoutAvailability.enabled} title={view.checkoutAvailability.disabledReason}>{view.primaryAction}</button></article></div></section>;
}
