import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";
const root = process.cwd();
function source(path: string) { return readFileSync(join(root, path), "utf8"); }
describe("E08 invoice quality recovery Product boundary", () => {
  it("keeps reusable quality/recovery components fixture-free", () => { expect(source("src/features/quality/QualityReviewPreview.tsx")).not.toContain("sample-data"); expect(source("src/features/quality/QualityReviewPreview.tsx")).not.toContain("sampleQualityCase"); expect(source("src/features/recovery/RecoveryActionsPreview.tsx")).not.toContain("sampleAttentionItems"); expect(source("src/features/recovery/RecoveryActionsPreview.tsx")).not.toContain("recoveryFixtures"); expect(source("src/features/quality/QualityReviewFixturePreview.tsx")).toContain("sampleQualityCase"); expect(source("src/features/recovery/RecoveryActionsFixturePreview.tsx")).toContain("sampleAttentionItems"); });
  it("uses exact command signatures and preserves server authority", () => { expect(source("src/features/invoices/server-boundary.ts")).toContain("applyManualPayment(ctx: ActorContext, invoiceId: string, input: ManualPaymentInput, meta: CommandMeta)"); expect(source("src/features/quality/server-boundary.ts")).toContain("applyQualityCaseAction(ctx: ActorContext, id: string, action: QualityCaseAction, input: QualityCaseActionInput, meta: CommandMeta)"); expect(source("src/features/quality/server-boundary.ts")).toContain("expectedVersion: input.qualityCase.version"); expect(source("src/features/invoices/server-boundary.ts")).not.toContain("balanceMinor ="); expect(source("src/features/quality/server-boundary.ts")).not.toContain("qualityCase.state ="); });
  it("keeps customer manual payment disabled and recovery read-only", () => { expect(source("src/features/invoices/server-boundary.ts")).toContain('role === "CUSTOMER"'); expect(source("src/features/recovery/RecoveryActionsPreview.tsx")).toContain("disabled"); expect(source("src/features/recovery/view-models.ts")).toContain("readOnly: true"); });
  it("validates expanded snapshots and preserves route coverage", () => { const snapshot = source("src/features/operations/workspace-snapshot-boundary.ts"); expect(snapshot).toContain("snapshot.qualityCases"); expect(snapshot).toContain("snapshot.attentionItems"); expect(snapshot).toContain("WORKSPACE_MISMATCH"); const route = source("src/features/operations/OperationalRoute.tsx"); for (const marker of ["BusinessPanel", "CustomerPanel", "StaffPanel", "CrewPanel", "OnboardingPanel", "TourPanel", "QualityReviewPreview", "RecoveryActionsPreview", "StaffInvoiceOperationalPreview"]) expect(route).toContain(marker); });
});
