import { ok as assert } from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";
const root = process.cwd();
const source = (path: string) => readFileSync(join(root, path), "utf8");
const route = source("src/features/operations/OperationalRoute.tsx");
const data = source("src/features/operations/route-data.ts");
const model = source("src/features/product/final-journey-model.ts");
const browserSpec = source("docs/execution/v1-e10-browser-acceptance.md");
assert(data.includes("ReportingSnapshotDTO") && data.includes("staff: {") && data.includes("reporting?: ReportingRouteSnapshot"), "E09 reporting data must be routable");
assert(data.includes("PlatformBillingSnapshotDTO") && data.includes("platformBilling?: PlatformBillingRouteSnapshot"), "E09 platform billing data must be routable");
assert(data.includes("OwnerSettingsSnapshotDTO") && data.includes("ownerSettings?: OwnerSettingsRouteSnapshot") && data.includes("onboarding?: OnboardingRouteSnapshot"), "owner settings/onboarding data must be routable");
assert(route.includes("<ReportsPreview snapshot={data.staff.reporting.snapshot}") && route.includes("<ReportsFixturePreview"), "reports route must pass server data or explicit fixture wrapper");
assert(route.includes("<PlatformBillingPreview snapshot={data.staff.platformBilling.snapshot}") && route.includes("<PlatformBillingFixturePreview"), "platform billing route must pass server data or explicit fixture wrapper");
assert(route.includes("<OwnerSettingsPreview embedded snapshot={data.staff.ownerSettings.snapshot}") && route.includes("<OwnerSettingsFixturePreview"), "settings route must pass server data or explicit fixture wrapper");
assert(route.includes("<OnboardingReadiness settings={data.onboarding.settings}") && route.includes("<OnboardingFixtureReadiness"), "onboarding route must pass server data or explicit fixture wrapper");
for (const path of ["src/features/reports/server-boundary.ts", "src/features/billing/server-boundary.ts", "src/features/settings/server-boundary.ts", "src/app/onboarding/server-actions.ts"]) { const file = source(path); assert(!file.includes("Repository"), `${path} must not import Core repositories`); assert(!file.includes("@/server/integrations"), `${path} must not import provider clients`); assert(!file.includes("stripe"), `${path} must not import Stripe/provider clients`); }
assert(source("src/features/reports/server-boundary.ts").includes("readReportingSnapshot(ctx: ActorContext, query: ReportingSnapshotQuery)"), "reporting boundary exact signature missing");
assert(source("src/features/billing/server-boundary.ts").includes("readPlatformBillingSnapshot(ctx: ActorContext)"), "platform billing boundary exact signature missing");
assert(source("src/features/settings/server-boundary.ts").includes("readOwnerSettingsSnapshot(ctx: ActorContext)"), "owner settings boundary exact signature missing");
for (const id of ["public-enquiry", "slot-checkout", "inbox", "crew-job", "field-evidence", "recurrence", "invoice-manual-payment", "quality", "recovery", "reports", "platform-billing", "settings", "onboarding"]) assert(model.includes(`id: "${id}"`), `guided journey missing ${id}`);
for (const role of ["visitor", "customer", "crew", "dispatcher", "owner"]) assert(model.includes(`role: "${role}"`), `role matrix missing ${role}`);
for (const recovery of ["authorization", "workspace mismatch", "version conflict", "slot stale", "hold expired", "payment review", "calendar stale", "provider config blocked", "reply suppressed", "usage limit reached", "quality resolution required", "recurrence conflict", "server failure"]) assert(model.includes(recovery), `error/recovery matrix missing ${recovery}`);
assert(!source("src/features/reports/ReportsPreview.tsx").includes("sample"), "ReportsPreview must not own sample data");
assert(!source("src/features/billing/PlatformBillingPreview.tsx").includes("PlatformPlanFixture"), "PlatformBillingPreview must not own plan fixture");
assert(!source("src/features/settings/OwnerSettingsPreview.tsx").includes("ServiceSettingFixture"), "OwnerSettingsPreview must not own service fixture");
assert(source("src/features/billing/PlatformBillingPreview.tsx").includes("Sandbox billing is never shown as live"), "sandbox payment must be labelled truthfully");
assert(browserSpec.includes("BROWSER_ACCEPTANCE=TO_RUN_CONFIGURATION_BLOCKED") && browserSpec.includes("desktop") && browserSpec.includes("tablet") && browserSpec.includes("mobile"), "browser acceptance spec must be explicit and blocked until executable runtime exists");
console.log("runtime-outage-e10-product-acceptance-harness PASS");
