import type { InvoiceDTO, PlatformBillingSnapshotDTO } from "@/contracts";
import { buildPlatformBillingView } from "./view-models";

interface PlatformBillingPreviewProps { snapshot?: PlatformBillingSnapshotDTO; customerInvoice?: InvoiceDTO }
export function PlatformBillingPreview({ snapshot, customerInvoice }: PlatformBillingPreviewProps) {
  if (!snapshot) return <section className="plain-card" aria-label="Platform billing boundary preview"><p className="eyebrow">Platform billing · server snapshot required</p><h2>Platform billing snapshot required</h2><p>Product cannot infer plan, status, usage or payment mode from local fixtures.</p></section>;
  const view = buildPlatformBillingView(snapshot, customerInvoice);
  return <section className="plain-card" aria-label="Platform billing boundary preview"><div className="section-heading compact"><p className="eyebrow">Platform billing · {view.modeLabel}</p><h2>Subscription status stays separate from customer cleaning payments</h2><p>{view.boundaryNotice}</p><span className="status-pill attention">{view.releaseLabel}</span></div><div className="card-grid two"><article className="mini-panel"><p className="label">Platform plan</p><h3>{view.planLabel} · {view.statusLabel}</h3><p>Provider mode: {view.modeLabel}</p>{view.modeLabel === "SANDBOX" && <p>Sandbox billing is never shown as live.</p>}</article><article className="mini-panel"><p className="label">Usage metrics</p>{view.usageRows.map((row) => <div key={row.label}><h3>{row.label}</h3><p>{row.value} · {row.state.replaceAll("_", " ")}</p></div>)}</article>{view.customerInvoiceLabel && <article className="mini-panel"><p className="label">Customer cleaning invoice</p><h3>{view.customerInvoiceLabel}</h3><p>This customer invoice does not affect the ServiceDesk platform plan.</p></article>}</div></section>;
}
