import type { IntegrationStatusDTO, OwnerSettingsSnapshotDTO, RecurrenceRuleDTO } from "@/contracts";
import { RecurrenceRulePreview } from "@/features/recurrence/RecurrenceRulePreview";
import { buildOwnerSettingsView } from "./view-models";

interface OwnerSettingsPreviewProps { embedded?: boolean; snapshot?: OwnerSettingsSnapshotDTO; integrations?: IntegrationStatusDTO[]; recurrence?: RecurrenceRuleDTO; sourceLabel?: "SERVER_SNAPSHOT" | "FIXTURE_UI_ONLY" }
export function OwnerSettingsPreview({ embedded = false, snapshot, integrations = [], recurrence, sourceLabel = "SERVER_SNAPSHOT" }: OwnerSettingsPreviewProps) {
  if (!snapshot) return <section className="plain-card" aria-label="Owner settings preview"><p className="eyebrow">Owner settings · server snapshot required</p><h2>Owner settings snapshot required</h2><p>Product does not invent services, rate versions, invitation emails, tokens or team state.</p></section>;
  const view = buildOwnerSettingsView({ snapshot, integrations, recurrence, sourceLabel });
  const content = <section className="plain-card" aria-label="Owner settings preview"><div className="section-heading compact"><p className="eyebrow">Owner settings · {view.dataSource}</p><h2>Services, team and provider health stay visible without exposing secrets</h2><p>Credentials, provider secrets and invitation tokens remain server-side.</p><span className="status-pill attention">{view.releaseLabel}</span></div><div className="card-grid three"><article className="mini-panel"><p className="label">Service catalog</p>{view.services.map((service) => <div key={service.code}><h3>{service.label}</h3><p>{service.code} · {service.stateLabel}</p></div>)}</article><article className="mini-panel"><p className="label">Team</p>{view.team.map((member) => <div key={member.id}><h3>{member.role}</h3><p>{member.stateLabel}</p></div>)}</article><article className="mini-panel"><p className="label">Integration health</p>{view.integrationHealth.map((integration) => <div key={integration.provider}><span className={`status-pill ${integration.ready ? "success" : "pending"}`}>{integration.stateLabel}</span><h3>{integration.provider.replaceAll("_", " ")}</h3><p>{integration.message}</p></div>)}</article></div>{recurrence && <RecurrenceRulePreview rule={recurrence} materializedVisits={[]} audience="staff" actionsInjected={false} sourceLabel={sourceLabel} />}<p>Secrets exposed: {view.exposesSecrets ? "yes" : "no"}.</p></section>;
  return embedded ? content : <div className="site-shell">{content}</div>;
}
