import type { RecurrenceRuleDTO, VisitDTO } from "@/contracts";
import type { ProductActionState } from "@/features/operations/action-state";
import type { RecurrenceRuleAction } from "@/server/core/facade";

export type RecurrenceAudience = "staff" | "customer";

export interface RecurrenceActionControl {
  action: RecurrenceRuleAction;
  label: string;
  enabled: boolean;
  disabledReason?: string;
}

export interface RecurrenceActionAvailability {
  audience: RecurrenceAudience;
  actionsInjected: boolean;
  controls: RecurrenceActionControl[];
}

export interface RecurrenceRuleViewInput {
  rule: RecurrenceRuleDTO;
  materializedVisits?: VisitDTO[];
  audience: RecurrenceAudience;
  actionsInjected?: boolean;
  actionState?: ProductActionState;
}

export interface RecurrenceRuleView {
  id: string;
  status: RecurrenceRuleDTO["status"];
  frequencyLabel: string;
  activeWindowLabel: string;
  occurrenceProgressLabel: string;
  nextOccurrenceLabel: string;
  timezoneLabel: string;
  localStartTimeLabel: string;
  authoritativeNextOccurrence: string | undefined;
  materializedVisitCards: Array<{ id: string; status: VisitDTO["status"]; startAt: string; crewLabel: string }>;
  actionAvailability: RecurrenceActionAvailability;
  actionState?: ProductActionState;
  noClientScheduleTruthLabel: string;
}

export function buildRecurrenceActionAvailability(input: {
  rule: RecurrenceRuleDTO;
  audience: RecurrenceAudience;
  actionsInjected?: boolean;
}): RecurrenceActionAvailability {
  if (input.audience === "customer") {
    return {
      audience: input.audience,
      actionsInjected: false,
      controls: [
        { action: "PAUSE", label: "Pause recurrence", enabled: false, disabledReason: "Customer recurrence mutation is disabled until Core explicitly authorizes it." },
        { action: "RESUME", label: "Resume recurrence", enabled: false, disabledReason: "Customer recurrence mutation is disabled until Core explicitly authorizes it." },
        { action: "SKIP_NEXT", label: "Skip next occurrence", enabled: false, disabledReason: "Customer recurrence mutation is disabled until Core explicitly authorizes it." },
      ],
    };
  }

  const missingServerAction = !input.actionsInjected;
  const disabledReason = missingServerAction
    ? "Inject accepted createRecurrenceRule/applyRecurrenceRuleAction server actions before enabling controls."
    : undefined;

  if (input.rule.status === "COMPLETED") {
    return {
      audience: input.audience,
      actionsInjected: Boolean(input.actionsInjected),
      controls: [
        { action: "PAUSE", label: "Pause recurrence", enabled: false, disabledReason: "Completed recurrence rules cannot be paused." },
        { action: "RESUME", label: "Resume recurrence", enabled: false, disabledReason: "Completed recurrence rules cannot be resumed." },
        { action: "SKIP_NEXT", label: "Skip next occurrence", enabled: false, disabledReason: "Completed recurrence rules cannot skip occurrences." },
      ],
    };
  }

  if (input.rule.status === "PAUSED") {
    return {
      audience: input.audience,
      actionsInjected: Boolean(input.actionsInjected),
      controls: [
        { action: "RESUME", label: "Resume recurrence", enabled: !missingServerAction, disabledReason },
      ],
    };
  }

  return {
    audience: input.audience,
    actionsInjected: Boolean(input.actionsInjected),
    controls: [
      { action: "PAUSE", label: "Pause recurrence", enabled: !missingServerAction, disabledReason },
      {
        action: "SKIP_NEXT",
        label: "Skip next occurrence",
        enabled: !missingServerAction && Boolean(input.rule.nextOccurrenceOn),
        disabledReason: input.rule.nextOccurrenceOn ? disabledReason : "Server has not supplied a nextOccurrenceOn value to skip.",
      },
    ],
  };
}

export function buildRecurrenceRuleView(input: RecurrenceRuleViewInput): RecurrenceRuleView {
  const rule = input.rule;
  const materializedVisits = input.materializedVisits ?? [];
  return {
    id: rule.id,
    status: rule.status,
    frequencyLabel: rule.frequency.replaceAll("_", " ").toLowerCase(),
    activeWindowLabel: `${rule.startsOn}${rule.endsOn ? ` → ${rule.endsOn}` : " → no server end date"}`,
    occurrenceProgressLabel: `${rule.generatedOccurrences}${rule.maxOccurrences ? ` / ${rule.maxOccurrences}` : ""} generated by server`,
    nextOccurrenceLabel: rule.nextOccurrenceOn ?? "No next occurrence supplied by server snapshot",
    timezoneLabel: rule.timezone,
    localStartTimeLabel: rule.localStartTime,
    authoritativeNextOccurrence: rule.nextOccurrenceOn,
    materializedVisitCards: materializedVisits.map((visit) => ({
      id: visit.id,
      status: visit.status,
      startAt: visit.startAt,
      crewLabel: visit.crewId ?? "unassigned",
    })),
    actionAvailability: buildRecurrenceActionAvailability({
      rule,
      audience: input.audience,
      actionsInjected: input.actionsInjected,
    }),
    actionState: input.actionState,
    noClientScheduleTruthLabel: "Product renders nextOccurrenceOn and materialized VisitDTOs only; it never generates recurrence dates.",
  };
}
