import type { IntegrationStatusDTO, OwnerSettingsSnapshotDTO } from "@/contracts";

type OnboardingState = "IMPLEMENTED" | "CONFIGURATION_BLOCKED";
export type OnboardingStepState = "COMPLETE" | "NEEDS_INPUT" | "CONFIGURATION_BLOCKED";
const providerLabels: Record<IntegrationStatusDTO["provider"], string> = { WHATSAPP: "WhatsApp", GOOGLE_CALENDAR: "Google Calendar", PAYMENT: "Payments", EMAIL: "Email", WEBHOOK: "Webhooks", AI: "AI assistant" };
export interface OnboardingReadinessItem { provider: IntegrationStatusDTO["provider"]; label: string; stateLabel: string; canClaimLive: boolean; detail: string }
export interface OnboardingReadinessView { overallState: OnboardingState; releaseNote: string; items: OnboardingReadinessItem[] }
export interface OnboardingSetupStep { key: "business" | "services" | "team" | "integrations" | "readiness"; label: string; state: OnboardingStepState; detail: string }
export interface OnboardingSetupView { readyToLaunch: boolean; launchLabel: string; steps: OnboardingSetupStep[] }
export function buildOnboardingReadinessView({ settings, integrations }: { settings?: OwnerSettingsSnapshotDTO; integrations: IntegrationStatusDTO[] }): OnboardingReadinessView { const items = integrations.map((integration) => { const canClaimLive = integration.status === "CONNECTED" && integration.mode === "LIVE"; return { provider: integration.provider, label: providerLabels[integration.provider], stateLabel: `${integration.status.replaceAll("_", " ")}${integration.mode ? ` · ${integration.mode}` : ""}`, canClaimLive, detail: integration.message ?? "No setup message recorded." }; }); const allLive = items.length > 0 && items.every((item) => item.canClaimLive); const hasOwnerInputs = Boolean(settings && settings.services.some((s) => s.enabled) && settings.members.some((m) => m.active)); return { overallState: allLive && hasOwnerInputs ? "IMPLEMENTED" : "CONFIGURATION_BLOCKED", releaseNote: allLive ? (hasOwnerInputs ? "Providers are live and owner setup exists; attach receipts before release." : "Providers are live, but service/team setup is owner input, not provider failure.") : "SANDBOX, BLOCKED, DEGRADED, REAUTH_REQUIRED and fixture modes are not live readiness." , items }; }
export function buildOnboardingSetupView({ settings, integrations }: { settings?: OwnerSettingsSnapshotDTO; integrations: IntegrationStatusDTO[] }): OnboardingSetupView { const readiness = buildOnboardingReadinessView({ settings, integrations }); const servicesReady = Boolean(settings?.services.some((s) => s.enabled)); const teamReady = Boolean(settings?.members.some((m) => m.active)); const integrationsLive = readiness.items.length > 0 && readiness.items.every((item) => item.canClaimLive); const steps: OnboardingSetupStep[] = [ { key: "business", label: "Business profile", state: settings ? "COMPLETE" : "NEEDS_INPUT", detail: "Business identity must come from owner settings." }, { key: "services", label: "Services", state: servicesReady ? "COMPLETE" : "NEEDS_INPUT", detail: servicesReady ? "At least one service is enabled." : "Missing service setup is owner input, not provider failure." }, { key: "team", label: "Team", state: teamReady ? "COMPLETE" : "NEEDS_INPUT", detail: teamReady ? "At least one team member is active." : "Missing team setup is owner input, not provider failure." }, { key: "integrations", label: "Integrations", state: integrationsLive ? "COMPLETE" : "CONFIGURATION_BLOCKED", detail: integrationsLive ? "All integrations are live." : "Sandbox/blocked/reauth/degraded integrations are not ready." }, { key: "readiness", label: "Launch readiness", state: readiness.overallState === "IMPLEMENTED" ? "COMPLETE" : "CONFIGURATION_BLOCKED", detail: readiness.releaseNote } ]; const readyToLaunch = steps.every((s) => s.state === "COMPLETE"); return { readyToLaunch, launchLabel: readyToLaunch ? "Ready for launch review" : "Launch blocked by configuration or owner input", steps }; }
