import type { ReportingSnapshotDTO } from "@/contracts";

interface ReportCard { label: string; value: string; evidence: string }
export interface ReportingView { cards: ReportCard[]; evidenceLabel: string; generatedAtLabel: string; sourceLabel: "SERVER_SNAPSHOT" | "FIXTURE_UI_ONLY" }

const money = (minor: number, currency = "USD") => new Intl.NumberFormat("en-US", { style: "currency", currency, maximumFractionDigits: 0 }).format(minor / 100);
const duration = (minutes: number) => { const h = Math.floor(minutes / 60); const m = minutes % 60; return `${h}h${m ? ` ${m}m` : ""}`; };
const bps = (value?: number) => typeof value === "number" ? `${(value / 100).toFixed(1)}%` : "No data";

export function buildReportingView(snapshot: ReportingSnapshotDTO, sourceLabel: "SERVER_SNAPSHOT" | "FIXTURE_UI_ONLY" = "SERVER_SNAPSHOT"): ReportingView {
  return {
    sourceLabel,
    generatedAtLabel: snapshot.generatedAt,
    evidenceLabel: `${sourceLabel}; generated by authoritative reporting snapshot, not recomputed from local Product records.`,
    cards: [
      { label: "Conversion", value: bps(snapshot.conversionRateBps), evidence: `${snapshot.bookedRequestCount} booked / ${snapshot.requestCount} requests` },
      { label: "Collected", value: money(snapshot.collectedMinor, snapshot.currency), evidence: `${money(snapshot.outstandingMinor, snapshot.currency)} outstanding` },
      { label: "Outstanding", value: money(snapshot.outstandingMinor, snapshot.currency), evidence: "Server-owned invoice aggregation" },
      { label: "Scheduled service", value: duration(snapshot.scheduledServiceMinutes), evidence: "Authoritative scheduled service minutes" },
      { label: "Scheduled buffer", value: duration(snapshot.scheduledBufferMinutes), evidence: "Authoritative buffer minutes" },
      { label: "Open attention", value: `${snapshot.openAttentionCount}`, evidence: "Open attention items from snapshot" },
      { label: "Unresolved quality", value: `${snapshot.unresolvedQualityCount}`, evidence: "Unresolved quality cases from snapshot" },
    ],
  };
}
