import type { AttentionItemDTO, IntegrationStatusDTO, InvoiceDTO, QualityCaseDTO, VisitDTO } from "@/contracts";
export type RecoveryKind = "DELIVERY_UNCERTAIN" | "CALENDAR_STALE" | "PAYMENT_REVIEW" | "QUALITY_REVIEW" | "INVOICE_REVIEW" | "GENERIC_HUMAN_REVIEW";
export interface RecoveryContext { invoice?: InvoiceDTO; visit?: VisitDTO; qualityCase?: QualityCaseDTO; }
export interface RecoveryActionView { releaseLabel: "CONFIGURATION_BLOCKED" | "IMPLEMENTED"; readOnly: true; items: Array<{ id: string; kind: RecoveryKind; summary: string; ownerLabel: string; action: string; proofLabel: string; canExecuteAutomatically: false; linkedAttentionCount: number; providerStatus?: string; resourceLabel: string; }>; }
function kindFor(item: AttentionItemDTO, context: RecoveryContext): RecoveryKind { if (item.type === "DELIVERY_UNCERTAIN") return "DELIVERY_UNCERTAIN"; if (item.type === "CALENDAR_STALE") return "CALENDAR_STALE"; if (item.type === "PAYMENT_REVIEW") return "PAYMENT_REVIEW"; if (item.resourceType === "quality" || item.resourceId === context.qualityCase?.id || item.type.includes("QUALITY")) return "QUALITY_REVIEW"; if (item.resourceType === "invoice" || item.resourceId === context.invoice?.id || item.type.includes("INVOICE") || item.type === "BALANCE_COLLECTION") return "INVOICE_REVIEW"; return "GENERIC_HUMAN_REVIEW"; }
function actionFor(kind: RecoveryKind): string { switch (kind) { case "DELIVERY_UNCERTAIN": return "Reconcile provider state before retry"; case "CALENDAR_STALE": return "Reconnect or refresh calendar before confirmation"; case "PAYMENT_REVIEW": return "Review payment and capacity before confirming visit"; case "QUALITY_REVIEW": return "Human quality owner must review and resolve"; case "INVOICE_REVIEW": return "Human staff must review invoice/payment state"; case "GENERIC_HUMAN_REVIEW": return "Human owner must review this attention item"; } }
function proofFor(kind: RecoveryKind): string { switch (kind) { case "DELIVERY_UNCERTAIN": return "No provider delivery proof"; case "CALENDAR_STALE": return "Calendar freshness not verified"; case "PAYMENT_REVIEW": return "Payment/capacity requires staff review"; case "QUALITY_REVIEW": return "Quality case requires human resolution"; case "INVOICE_REVIEW": return "Invoice/payment balance requires human review"; case "GENERIC_HUMAN_REVIEW": return "Human-owned attention item"; } }
function providerFor(kind: RecoveryKind): IntegrationStatusDTO["provider"] | undefined { if (kind === "DELIVERY_UNCERTAIN") return "WHATSAPP"; if (kind === "CALENDAR_STALE") return "GOOGLE_CALENDAR"; if (kind === "PAYMENT_REVIEW" || kind === "INVOICE_REVIEW") return "PAYMENT"; return undefined; }
export function buildRecoveryActionsView({ attentionItems, integrations, context = {} }: { attentionItems: readonly AttentionItemDTO[]; integrations: readonly IntegrationStatusDTO[]; context?: RecoveryContext }): RecoveryActionView { const items = attentionItems.map((attention) => { const kind = kindFor(attention, context); const provider = providerFor(kind); const integration = provider ? integrations.find((candidate) => candidate.provider === provider) : undefined; return { id: attention.id, kind, summary: attention.summary, ownerLabel: attention.ownerUserId ?? "Unassigned", action: actionFor(kind), proofLabel: proofFor(kind), canExecuteAutomatically: false as const, linkedAttentionCount: attentionItems.filter((item) => item.resourceId === attention.resourceId || item.type === attention.type).length, providerStatus: integration ? `${integration.status.replaceAll("_", " ")}${integration.mode ? ` · ${integration.mode}` : ""}` : undefined, resourceLabel: `${attention.resourceType}:${attention.resourceId}` }; }); const configurationBlocked = integrations.some((integration) => integration.mode !== "LIVE" || integration.status !== "CONNECTED"); return { releaseLabel: configurationBlocked ? "CONFIGURATION_BLOCKED" : "IMPLEMENTED", readOnly: true, items }; }
