import type { ActorContext, CommandMeta, QuoteDTO, Result } from "@/contracts";
import { productActionFailure, productActionSuccess, type ProductActionError, type ProductActionResult } from "@/features/operations/server-action-adapters";

export interface CustomerQuoteAcceptancePort {
  acceptQuote(ctx: ActorContext, quoteId: string, meta: CommandMeta): Promise<Result<QuoteDTO>>;
}

export interface CustomerQuoteAcceptanceInput {
  ctx: ActorContext;
  quote: QuoteDTO;
  idempotencyKey: string;
  now: string;
}

export interface QuoteAcceptanceAvailability {
  enabled: boolean;
  label: string;
  disabledReason?: string;
  pending?: boolean;
}

const acceptableStatuses: QuoteDTO["status"][] = ["SENT", "APPROVED"];

function failure(error: { code: string; message: string }): ProductActionError {
  return { code: error.code, message: error.message };
}

export function buildQuoteAcceptanceAvailability(quote: QuoteDTO, handlerInjected: boolean, pending = false): QuoteAcceptanceAvailability {
  if (pending) return { enabled: false, pending, label: "Accepting quote", disabledReason: "Quote acceptance is already pending." };
  if (!handlerInjected) return { enabled: false, label: "Accept quote unavailable", disabledReason: "No accepted server quote acceptance handler is injected." };
  if (quote.status === "EXPIRED") return { enabled: false, label: "Quote expired", disabledReason: "Expired quotes must be regenerated by staff." };
  if (!acceptableStatuses.includes(quote.status)) return { enabled: false, label: "Quote cannot be accepted", disabledReason: `Quote status ${quote.status} is not customer-acceptance eligible.` };
  return { enabled: true, label: "Accept quote" };
}

export function createCustomerQuoteAcceptanceFactory(port: CustomerQuoteAcceptancePort) {
  return async function acceptCustomerQuote(input: CustomerQuoteAcceptanceInput): Promise<ProductActionResult<QuoteDTO>> {
    const steps = ["acceptQuote"];
    if (input.quote.workspaceId !== input.ctx.workspaceId) {
      return productActionFailure(failure({ code: "WORKSPACE_MISMATCH", message: "Quote belongs to a different workspace." }), steps, "acceptQuote");
    }
    const availability = buildQuoteAcceptanceAvailability(input.quote, true);
    if (!availability.enabled) {
      return productActionFailure(failure({ code: input.quote.status === "EXPIRED" ? "QUOTE_EXPIRED" : "INVALID_QUOTE_STATE", message: availability.disabledReason ?? "Quote cannot be accepted." }), steps, "acceptQuote");
    }
    const result = await port.acceptQuote(input.ctx, input.quote.id, {
      expectedVersion: input.quote.version,
      idempotencyKey: input.idempotencyKey,
      now: input.now,
    });
    return result.ok
      ? productActionSuccess(result.value, steps, "Quote acceptance accepted by the server. Use returned QuoteDTO only.")
      : productActionFailure(failure(result), steps, "acceptQuote");
  };
}
